apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: modresort-app-subscription
  namespace: modresort
  labels:
    app: modresort-app
  annotations:
    apps.open-cluster-management.io/git-path: apps/modresort/
    apps.open-cluster-management.io/git-branch: stage
spec:
  channel: open-cluster-management/acm-modresort
  placement:
    placementRef:
      kind: PlacementRule
      name: development-clusters
